FROM ruby:3.4.4

# 必要なパッケージのインストール
RUN apt-get update -qq && \
    apt-get install -y build-essential libpq-dev nodejs

# 作業ディレクトリの設定
WORKDIR /rails

# GemfileとGemfile.lockのコピー
COPY Gemfile Gemfile.lock ./

# Bundlerを使用して依存関係をインストール
RUN bundle install

# アプリケーションコードのコピー
COPY . .

CMD ["bash", "-c", "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b 'ssl://0.0.0.0:3000?key=./localhost-key.pem&cert=./localhost.pem'"]
